name: Build
on:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: mkdir
      run: |
        mkdir work
    - name: test1
      run: |
        echo "check pwd"
        pwd
        ls -la
    - name: test2 - cd to workdir
      working-directory: ./work
      run: |
        echo "check pwd"
        pwd
        ls -la
    - name: test3
      working-directory: ./work
      run: |
        touch testFile.txt test0.txt
        result=false
        fpaths="$(find . -type f -name *.txt)"
        for fpath in $fpaths; do
          if [[ "$(basename $fpath)" == *tF* ]]; then
            result=true
            echo $fname
            echo $result
          fi
        done
